services:
  - type: web
    name: ksef-api
    runtime: docker
    dockerfilePath: src/KSeFGateway.Api/Dockerfile
    dockerContext: src
    plan: free
    healthCheckPath: /health
    envVars:
      - key: KSEF_TOKEN
        sync: false
      - key: KSEF_NIP
        sync: false
      - key: KSEF_ENV
        value: TEST
      - key: PDF_SERVICE_URL
        fromService:
          name: ksef-pdf
          type: web
          property: hostport
      - key: GITHUB_PAT
        sync: false
      - key: DOCKER_BUILDKIT
        value: "1"
    buildFilter:
      paths:
        - src/**

  - type: web
    name: ksef-pdf
    runtime: docker
    dockerfilePath: pdf-service/Dockerfile
    dockerContext: pdf-service
    plan: free
    healthCheckPath: /health
    buildFilter:
      paths:
        - pdf-service/**
